### ISSUE TITLE
How to use visual studio run your project?

### ISSUE THREAD

**Issue by yezi205** [shinn716/Unity-FFmpeg-ScreenRecorder#3]

**Comment by shinn716** [comment]
You need Unity Editor to open the project. (https://unity.com/)
If you want to use ffmpeg only.
You can download ffbinary from this site: https://ffbinaries.com/downloads
Use terminal send command to ffmpeg.
Ex: Convert video to H.264 
`ffmpeg -i video.avi output.mp4`
![image](https://user-images.githubusercontent.com/3417707/208631069-65674d8e-9d8e-4f81-9d77-25c4938c3d8c.png)
